### PR TITLE
A test pr

### PR DESCRIPTION
**Pull request by baldwmic**
Can a bot comment?

### CODE REVIEW

**Comment by baldwmic** [comment]
hi! -a bot

**Comment by baldwmic** [comment]
@cashc u mad bro?

**Comment by baldwmic** [comment]
```
test 1
```

**Comment by baldwmic** [comment]
${comment}

**Comment by baldwmic** [comment]
test 3

**Comment by cashc** [comment]
There are `10` types of people in this world. Those who know binary and those who don't.

**Comment by baldwmic** [comment]
test 5

**Comment by baldwmic** [comment]
heya!

**Comment by baldwmic** [comment]
joker

**Comment by baldwmic** [comment]
hi eric

**Comment by baldwmic** [comment]
'BABEL_ENV=test ./node_modules/.bin/jest --config jest.json svg --no-cache --coverage

**Comment by baldwmic** [comment]
'BABEL_ENV=test ./node_modules/.bin/jest --config jest.json svg --no-cache --coverage

**Comment by baldwmic** [comment]
'BABEL_ENV=test ./node_modules/.bin/jest --config jest.json svg --no-cache --coverage

**Comment by neurosnap** [comment]
suck it bash

**Comment by neurosnap** [comment]
---------------|----------|----------|----------|----------|----------------|
File           |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------|----------|----------|----------|----------|----------------|
All files      |    88.89 |    69.57 |       55 |     93.1 |                |
 test-util     |    78.57 |      100 |        0 |      100 |                |
  jest.js      |    78.57 |      100 |        0 |      100 |                |
 ui/components |    91.84 |    69.57 |      100 |    91.49 |                |
  svg.js       |    91.84 |    69.57 |      100 |    91.49 |   58,92,95,126 |
---------------|----------|----------|----------|----------|----------------|

**Comment by baldwmic** [comment]
```
------------------------|----------|----------|----------|----------|----------------|
File                    |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------------|----------|----------|----------|----------|----------------|
All files               |    76.13 |     44.9 |    60.87 |    80.42 |                |
 test-util              |       80 |      100 |        0 |      100 |                |
  jest.js               |       80 |      100 |        0 |      100 |                |
 ui/components          |    71.15 |    43.18 |    82.14 |    72.55 |                |
  context-menu-items.js |    91.67 |       50 |      100 |    91.67 |             67 |
  context-menu.js       |    83.72 |    68.42 |    72.73 |    83.72 |... 141,151,152 |
  svg.js                |     55.1 |    21.74 |    81.82 |    57.45 |... ,95,103,126 |
 ui/styles              |      100 |      100 |      100 |      100 |                |
  clickable.js          |      100 |      100 |      100 |      100 |                |
 updater                |    88.57 |       60 |       50 |      100 |                |
  action-creators.js    |       60 |        0 |       20 |      100 |           4,21 |
  action-types.js       |      100 |      100 |      100 |      100 |                |
  effects.js            |      100 |      100 |      100 |      100 |                |
------------------------|----------|----------|----------|----------|----------------|

```

**Comment by baldwmic** [comment]
```
------------------------|----------|----------|----------|----------|----------------|
File                    |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------------|----------|----------|----------|----------|----------------|
All files               |    76.13 |     44.9 |    60.87 |    80.42 |                |
 test-util              |       80 |      100 |        0 |      100 |                |
  jest.js               |       80 |      100 |        0 |      100 |                |
 ui/components          |    71.15 |    43.18 |    82.14 |    72.55 |                |
  context-menu-items.js |    91.67 |       50 |      100 |    91.67 |             67 |
  context-menu.js       |    83.72 |    68.42 |    72.73 |    83.72 |... 141,151,152 |
  svg.js                |     55.1 |    21.74 |    81.82 |    57.45 |... ,95,103,126 |
 ui/styles              |      100 |      100 |      100 |      100 |                |
  clickable.js          |      100 |      100 |      100 |      100 |                |
 updater                |    88.57 |       60 |       50 |      100 |                |
  action-creators.js    |       60 |        0 |       20 |      100 |           4,21 |
  action-types.js       |      100 |      100 |      100 |      100 |                |
  effects.js            |      100 |      100 |      100 |      100 |                |
------------------------|----------|----------|----------|----------|----------------|

```

**Comment by baldwmic** [comment]
```

=============================== Coverage summary ===============================
Statements   : 85.53% ( 136/159 )
Branches     : 71.43% ( 50/70 )
Functions    : 68.42% ( 39/57 )
Lines        : 86.75% ( 131/151 )
================================================================================

```

**Comment by baldwmic** [comment]
```
=============================== Coverage summary ===============================
Statements   : 85.53% ( 136/159 )
Branches     : 71.43% ( 50/70 )
Functions    : 68.42% ( 39/57 )
Lines        : 86.75% ( 131/151 )
================================================================================
```

**Comment by baldwmic** [comment]
no longer need this for testing

**Pull request closed without merging**
